import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;`);
for(const file of ['schema.sql','migrations/002_exports_v2.sql','migrations/003_sector_access.sql','migrations/004_operations_admin_media.sql','migrations/005_review_fixes.sql','migrations/006_sector_export_quantity.sql','migrations/007_sector_devices.sql'])await db.exec(fs.readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
const store=randomUUID(),admin=randomUUID(),kitchen=randomUUID(),bakery=randomUUID(),intruder=randomUUID();
await db.query('insert into stores values($1,$2)',[store,'Loja']);
for(const id of [admin,kitchen,bakery,intruder]) await db.query('insert into auth.users(id) values($1)',[id]);
const adminCode=(await db.query("select provision_sector_device($1,'admin') body",[store])).rows[0].body.code;
const login=id=>db.exec(`set role authenticated;set request.jwt.claim.sub='${id}'`);
const activate=(code,device=randomUUID())=>db.query('select activate_sector_device($1,$2,$3) body',[store,device,code]);
await login(intruder);await assert.rejects(()=>activate('A'.repeat(32)));
await assert.rejects(()=>db.query("select provision_sector_device($1,'admin')",[store]));
await assert.rejects(()=>db.query('select * from sector_devices'));
await assert.rejects(()=>db.query("select admin_provision_sector($1,'cozinha',false,'Instalação')",[store]));
await login(admin);const adminDevice=randomUUID();await activate(adminCode,adminDevice);
assert.equal((await activate(adminCode,adminDevice)).rows[0].body.duplicate,true);
await assert.rejects(()=>activate(adminCode));
const issue=(slot,replace=false)=>db.query('select admin_provision_sector($1,$2,$3,$4) body',[store,slot,replace,'Instalação autorizada']);
const code=(await issue('cozinha')).rows[0].body.code;
await login(kitchen);const kitchenDevice=randomUUID();await activate(code,kitchenDevice);
assert.deepEqual((await db.query('select role,sector from memberships where user_id=$1',[kitchen])).rows[0],{role:'operator',sector:'cozinha'});
await assert.rejects(()=>issue('padaria'));
await login(intruder);await assert.rejects(()=>activate(code,kitchenDevice));
await login(admin);await assert.rejects(()=>issue('cozinha'));
await assert.rejects(()=>db.query("select admin_set_member($1,$2,'operator','padaria',true)",[store,kitchen]));
await assert.rejects(()=>db.query("select admin_set_member($1,$2,'operator','cozinha',true)",[store,intruder]));
const bakeryCode=(await issue('padaria')).rows[0].body.code;
await login(kitchen);await assert.rejects(()=>activate(bakeryCode,kitchenDevice));
await login(bakery);await activate(bakeryCode);
await login(admin);const expired=(await issue('hortifruti')).rows[0].body.code;
await db.exec('reset role');await db.query("update sector_devices set expires_at=now()-interval '1 hour' where slot='hortifruti'");
await login(intruder);await assert.rejects(()=>activate(expired));
await login(admin);const newKitchenCode=(await issue('cozinha',true)).rows[0].body.code;
await login(kitchen);assert.equal((await db.query('select * from memberships')).rows.length,0);await assert.rejects(()=>activate(code,kitchenDevice));
await login(intruder);await activate(newKitchenCode);
await login(admin);await db.query("select admin_set_member($1,$2,'operator','cozinha',false)",[store,intruder]);
await login(intruder);await assert.rejects(()=>activate(newKitchenCode));
console.log('PASS: ativação sem e-mail, acesso negado antes de ativar, código forte/expiração/reenvio, um aparelho por setor, papel fixo, substituição e revogação sem ressurreição');
await db.close();
