import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;`);
for(const file of ['schema.sql','migrations/002_exports_v2.sql','migrations/003_sector_access.sql','migrations/004_operations_admin_media.sql','migrations/005_review_fixes.sql','migrations/006_sector_export_quantity.sql','migrations/007_sector_devices.sql','migrations/008_multiple_sector_devices.sql'])await db.exec(fs.readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
const store=randomUUID(),admin=randomUUID(),second=randomUUID(),actor=randomUUID(),intruder=randomUUID();
await db.query('insert into stores values($1,$2)',[store,'Loja']);
for(const id of [admin,second,actor,intruder])await db.query('insert into auth.users(id) values($1)',[id]);
const login=id=>db.exec(`set role authenticated;set request.jwt.claim.sub='${id}'`);
let upgraded=false;
const activate=(code,device,allow=false)=>db.query(upgraded ? 'select activate_sector_device($1,$2,$3,$4) body' : 'select activate_sector_device($1,$2,$3) body',upgraded ? [store,device,code,allow] : [store,device,code]);
const initial=(await db.query("select provision_sector_device($1,'admin') body",[store])).rows[0].body.code;
const adminDevice=randomUUID();await login(admin);await activate(initial,adminDevice);
await db.exec('reset role');await db.exec(fs.readFileSync(new URL('../supabase/migrations/009_activation_and_scope_changes.sql',import.meta.url),'utf8'));
upgraded=true;
await login(admin);
const issue=slot=>db.query('select admin_provision_sector($1,$2,false,$3) body',[store,slot,'Autorizar aparelho']);
const kitchenCode=(await issue('cozinha')).rows[0].body.code;
const lastAdminCode=(await issue('padaria')).rows[0].body.code;
await assert.rejects(()=>activate(lastAdminCode,adminDevice,true));
const secondCode=(await issue('admin')).rows[0].body.code;
await login(second);await activate(secondCode,randomUUID());
await login(admin);const targetCode=(await issue('padaria')).rows[0].body.code;
const device=randomUUID();await login(actor);await activate(kitchenCode,device);
await assert.rejects(()=>activate(targetCode,randomUUID()));
await assert.rejects(()=>activate(targetCode,device));
await activate(targetCode,device,true);
assert.equal((await db.query('select sector from memberships where user_id=$1',[actor])).rows[0].sector,'padaria');
assert.equal((await activate(targetCode,device)).rows[0].body.duplicate,true);
await assert.rejects(()=>activate(kitchenCode,device));
await login(intruder);await assert.rejects(()=>activate(kitchenCode,randomUUID()));
await assert.rejects(()=>activate(targetCode,device));await assert.rejects(()=>issue('admin'));
await login(admin);await activate(lastAdminCode,adminDevice,true);
assert.equal((await db.query('select role,sector from memberships where user_id=$1',[admin])).rows[0].role,'operator');
await login(second);assert.equal((await db.query('select admin_members($1) body',[store])).rows[0].body.filter(x=>x.role==='admin').length,1);
await assert.rejects(()=>db.query("select admin_set_member($1,$2,'admin',null,false)",[store,second]));
await assert.rejects(()=>db.query("select admin_set_member($1,$2,'operator','cozinha',true)",[store,actor]));
console.log('PASS: 009 preserva admin existente, permite admin adicional, exige código novo para trocar setor, invalida código antigo, protege instalação/último administrador e registra auditoria');
await db.close();
