import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;`);
for(const file of ['schema.sql','migrations/002_exports_v2.sql','migrations/003_sector_access.sql','migrations/004_operations_admin_media.sql','migrations/005_review_fixes.sql','migrations/006_sector_export_quantity.sql','migrations/007_sector_devices.sql'])await db.exec(fs.readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
const store=randomUUID(),admin=randomUUID(),a=randomUUID(),b=randomUUID(),c=randomUUID(),bakery=randomUUID(),intruder=randomUUID();
await db.query('insert into stores values($1,$2)',[store,'Loja']);
for(const id of [admin,a,b,c,bakery,intruder])await db.query('insert into auth.users(id) values($1)',[id]);
const login=id=>db.exec(`set role authenticated;set request.jwt.claim.sub='${id}'`);
const activate=(code,device)=>db.query('select activate_sector_device($1,$2,$3) body',[store,device,code]);
const adminCode=(await db.query("select provision_sector_device($1,'admin') body",[store])).rows[0].body.code;
const oldCode=(await db.query("select provision_sector_device($1,'cozinha') body",[store])).rows[0].body.code;
const oldPending=(await db.query("select provision_sector_device($1,'padaria') body",[store])).rows[0].body.code;
await login(admin);await activate(adminCode,randomUUID());
const da=randomUUID(),dbb=randomUUID();await login(a);await activate(oldCode,da);
await db.exec('reset role');await db.exec(fs.readFileSync(new URL('../supabase/migrations/008_multiple_sector_devices.sql',import.meta.url),'utf8'));
await login(a);assert.equal((await activate(oldCode,da)).rows[0].body.duplicate,true);
await login(bakery);await activate(oldPending,randomUUID());
await login(admin);
const issue=(slot,replace=false)=>db.query('select admin_provision_sector($1,$2,$3,$4) body',[store,slot,replace,'Adicionar máquina']);
const cb=(await issue('cozinha')).rows[0].body.code,cc=(await issue('cozinha')).rows[0].body.code;
assert.notEqual(cb,cc);await assert.rejects(()=>issue('cozinha',true));
await login(b);await activate(cb,dbb);await login(c);await activate(cc,randomUUID());
await login(intruder);await assert.rejects(()=>activate(cb,dbb));await assert.rejects(()=>issue('cozinha'));
await assert.rejects(()=>db.query('select * from sector_devices'));
await login(a);await assert.rejects(()=>activate(cc,da));
await login(admin);assert.equal((await db.query('select admin_members($1) body',[store])).rows[0].body.filter(m=>m.sector==='cozinha').length,3);
await assert.rejects(()=>db.query("select admin_set_member($1,$2,'operator','padaria',true)",[store,b]));
const expired=(await issue('hortifruti')).rows[0].body.code;
await db.exec('reset role');await db.query("update sector_devices set expires_at=now()-interval '1 hour' where store_id=$1 and code_hash=encode(sha256(convert_to($2,'UTF8')),'hex')",[store,expired]);
await login(intruder);await assert.rejects(()=>activate(expired,randomUUID()));
const device=randomUUID();
const apply=(kind,body,expected=0)=>db.query('select apply_operation($1,$2,$3,$4,$5,$6::jsonb)',[store,randomUUID(),device,kind,expected,JSON.stringify(body)]);
await login(admin);
const product={id:randomUUID(),code:'000125',description:'Produto',unit:'KG',active:true,version:1,sectors:['cozinha'],photo:null};await apply('product',product);
async function consume(actor,amount){
 await login(actor);
 const body={id:randomUUID(),date:'2026-10-06',created_at:'2026-10-06T12:00:00Z',operator:'Cozinha',sector:'cozinha',note:'',status:'confirmed',version:1,items:[{id:randomUUID(),product_id:product.id,code:product.code,description:product.description,unit:'KG',amount,total_cents:100}]};
 await apply('consumption',body);return body;
}
const ca=await consume(a,1000),consB=await consume(b,2000),cancelled=await consume(a,500);
await login(b);assert.equal((await db.query("select count(*)::int n from entities where kind='consumption'")).rows[0].n,3);
await apply('consumption',{...cancelled,status:'cancelled',version:2,cancellation_reason:'Registro duplicado',cancelled_at:'2026-10-06T13:00:00Z'},1);
await login(bakery);assert.equal((await db.query('select * from entities')).rows.length,0);
await assert.rejects(()=>apply('consumption',{...ca,status:'cancelled',version:2,cancellation_reason:'Outro setor',cancelled_at:'2026-10-06T13:00:00Z'},1));
const profile={version:1,separator:';',decimal:',',encoding:'UTF8',line_ending:'CRLF',header:false,bom:false,fixed_price:false,validated:true,order:['code','quantity','unit','unit_price']};
const item=c=>({consumption_id:c.id,item_id:c.items[0].id,version:c.version});
const batch=cs=>db.query('select create_export_batch_v3($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6) body',[store,randomUUID(),JSON.stringify(cs.map(item)),JSON.stringify(profile),'{}','cozinha']);
await login(b);await assert.rejects(()=>batch([ca,consB]));
await login(admin);const first=(await batch([ca,consB])).rows[0].body;
assert.equal(Buffer.from(first.artifact.base64,'base64').toString('utf8'),'000125;3\r\n');
const next=await consume(c,1000);await login(admin);
const second=(await batch([ca,consB,next])).rows[0].body;assert.equal(second.skipped_count,2);
assert.equal(Buffer.from(second.artifact.base64,'base64').toString('utf8'),'000125;1\r\n');
await login(a);await assert.rejects(()=>apply('consumption',{...ca,status:'cancelled',version:2,cancellation_reason:'Já exportado',cancelled_at:'2026-10-06T14:00:00Z'},1));
await login(admin);
await db.query("select admin_set_member($1,$2,'operator','cozinha',false)",[store,b]);
await login(b);assert.equal((await db.query('select * from memberships')).rows.length,0);await assert.rejects(()=>activate(cb,dbb));
await login(a);assert.equal((await db.query('select * from memberships')).rows.length,1);assert.equal((await activate(oldCode,da)).rows[0].body.duplicate,true);
await login(c);assert.equal((await db.query('select * from memberships')).rows.length,1);
await db.exec('reset role');
await assert.rejects(()=>db.query("select provision_sector_device($1,'admin',false)",[store]));
const recovery=(await db.query("select provision_sector_device($1,'admin',true) body",[store])).rows[0].body.code;
await login(admin);await assert.rejects(()=>activate(adminCode,randomUUID()));
await login(intruder);await activate(recovery,randomUUID());
assert.equal((await db.query('select admin_members($1) body',[store])).rows[0].body.filter(m=>m.sector==='cozinha').length,2);
console.log('PASS: 008 preserva ativações e códigos, múltiplas máquinas, códigos independentes de uso único, expiração, setor fixo, revogação individual, RLS, cancelamento compartilhado e exportação agregada sem duplicidade');
await db.close();
