import {PGlite}from'@electric-sql/pglite';import fs from'node:fs';import assert from'node:assert/strict';import{randomUUID,createHash}from'node:crypto';
const db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;`);
for(const file of['schema.sql','migrations/002_exports_v2.sql','migrations/003_sector_access.sql','migrations/004_operations_admin_media.sql'])await db.exec(fs.readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
const store=randomUUID(),admin=randomUUID(),operator=randomUUID(),device=randomUUID();await db.query('insert into auth.users values($1,$2),($3,$4)',[admin,'admin@test',operator,'operator@test']);await db.query('insert into stores values($1,$2)',[store,'Loja']);await db.query("insert into memberships(store_id,user_id,role,sector)values($1,$2,'admin',null),($1,$3,'operator','cozinha')",[store,admin,operator]);await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
const photo=Buffer.from('foto antiga').toString('base64'),hash=createHash('sha256').update(Buffer.from(photo,'base64')).digest('hex');
const product={id:randomUUID(),code:'01',description:'Produto',unit:'UN',active:true,version:1,sectors:['cozinha'],photo};
const apply=(body,id=randomUUID(),kind='product',expected=0)=>db.query('select apply_operation($1,$2,$3,$4,$5,$6::jsonb) result',[store,id,device,kind,expected,JSON.stringify(body)]);
const op=randomUUID(),metadataOp=randomUUID();await apply(product,op);
const metadataProduct={...product,id:randomUUID(),code:'02',photo:null,photo_hash:hash};await apply(metadataProduct,metadataOp);
await db.exec('reset role');
await db.query("update operations set received_at='2025-01-02T03:04:05Z' where store_id=$1 and id=$2",[store,op]);
await db.query("update audit_log set action='historical_product' where source_key=$1",['operation:'+store+':'+op]);
await db.exec(fs.readFileSync(new URL('../supabase/migrations/005_review_fixes.sql',import.meta.url),'utf8'));await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
assert.equal(new Date((await db.query('select occurred_at from audit_log where source_key=$1',['operation:'+store+':'+op])).rows[0].occurred_at).toISOString(),'2025-01-02T03:04:05.000Z');
assert.equal((await apply(product,op)).rows[0].result.duplicate,true);
assert.equal((await apply({...metadataProduct,photo,photo_hash:undefined},metadataOp)).rows[0].result.duplicate,true);
assert.equal((await db.query('select data_base64 from product_images where hash=$1',[hash])).rows[0].data_base64,photo);
const fresh={...product,id:randomUUID(),code:'03'},freshOp=randomUUID();await apply(fresh,freshOp);assert.equal((await apply(fresh,freshOp)).rows[0].result.duplicate,true);
let saved=(await db.query('select body from entities where id=$1',[fresh.id])).rows[0].body;assert.equal(saved.photo,null);assert.equal(saved.photo_hash,hash);
await assert.rejects(()=>apply({...fresh,description:'Outro'},freshOp));
await assert.rejects(()=>apply({...product,id:randomUUID(),code:'04',photo_hash:'BAD'}));
await assert.rejects(()=>apply({...product,id:randomUUID(),code:'04',photo_hash:'0'.repeat(64)}));
const newPhoto=Buffer.from('foto nova').toString('base64'),newHash=createHash('sha256').update(Buffer.from(newPhoto,'base64')).digest('hex');await apply({...fresh,version:2,photo:newPhoto},randomUUID(),'product',1);await apply(fresh,freshOp);saved=(await db.query('select body from entities where id=$1',[fresh.id])).rows[0].body;assert.equal(saved.version,2);assert.equal(saved.photo_hash,newHash);
await assert.rejects(()=>db.query('select apply_operation_checked($1,$2,$3,$4,$5,$6::jsonb)',[store,randomUUID(),device,'product',0,JSON.stringify({...product,id:randomUUID(),code:'05'})]));
await db.exec(`set request.jwt.claim.sub='${operator}'`);
const consume={id:randomUUID(),date:'2026-10-04',created_at:'2026-10-04T12:00:00Z',operator:'Ana',sector:'cozinha',note:'',status:'confirmed',version:1,cancellation_reason:null,items:[{id:randomUUID(),product_id:fresh.id,code:'FORJADO',description:'Produto',unit:'UN',amount:1000,total_cents:100}]};await assert.rejects(()=>apply(consume,randomUUID(),'consumption'));
consume.items[0].code='03';await apply(consume,randomUUID(),'consumption');
await assert.rejects(()=>apply({...product,id:randomUUID(),code:'05'}));
const huge=Buffer.alloc(20*1024*1024+1,0),digest=createHash('sha256').update(huge).digest('hex');await assert.rejects(()=>db.query('select upload_device_backup($1,$2,$3,$4)',[store,device,digest,huge.toString('base64')]));
console.log('PASS: reenvio estável de fotos inline/v4, separação atômica, rejeição de adulteração, versão nova preservada, código interno validado, validador privado e limite exato de backup e data histórica de auditoria');await db.close();
