import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid()returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid()to authenticated;`);
for(const file of ['schema.sql','migrations/002_exports_v2.sql','migrations/003_sector_access.sql','migrations/004_operations_admin_media.sql','migrations/005_review_fixes.sql']) await db.exec(fs.readFileSync(new URL('../supabase/'+file,import.meta.url),'utf8'));
const store=randomUUID(),admin=randomUUID(),operator=randomUUID(),device=randomUUID();
await db.query('insert into auth.users values($1,$2),($3,$4)',[admin,'admin@test',operator,'operator@test']);
await db.query('insert into stores values($1,$2)',[store,'Loja']);
await db.query("insert into memberships(store_id,user_id,role,sector) values($1,$2,'admin',null),($1,$3,'operator','cozinha')",[store,admin,operator]);
await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
const apply=(kind,body)=>db.query('select apply_operation($1,$2,$3,$4,0,$5::jsonb)',[store,randomUUID(),device,kind,JSON.stringify(body)]);
const product={id:randomUUID(),code:'000125',description:'Produto',unit:'KG',active:true,version:1,sectors:['cozinha','padaria','hortifruti'],photo:null};await apply('product',product);
async function consumption(sector,amount){
 const c={id:randomUUID(),date:'2026-10-05',created_at:'2026-10-05T12:00:00Z',operator:'Ana',sector,note:'',status:'confirmed',version:1,items:[{id:randomUUID(),product_id:product.id,code:product.code,description:product.description,unit:'KG',amount,total_cents:100}]};
 await apply('consumption',c);return c;
}
const profile={version:1,separator:';',decimal:',',encoding:'UTF8',line_ending:'CRLF',header:false,bom:false,fixed_price:false,validated:true,order:['code','quantity','unit','unit_price']};
const item=c=>({consumption_id:c.id,item_id:c.items[0].id,version:c.version});
const batch=(sector,cs,p=profile,id=randomUUID())=>db.query('select create_export_batch_v3($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6) body',[store,id,JSON.stringify(cs.map(item)),JSON.stringify(p),'{}',sector]);
const text=b=>Buffer.from(b.artifact.base64,'base64').toString('utf8');
const oldConsumption=await consumption('cozinha',1000),oldId=randomUUID();
const oldBatch=(await batch('cozinha',[oldConsumption],profile,oldId)).rows[0].body;
assert.equal(text(oldBatch).trim().split(';').length,4);
await db.exec('reset role');await db.exec(fs.readFileSync(new URL('../supabase/migrations/006_sector_export_quantity.sql',import.meta.url),'utf8'));await db.exec(`set role authenticated;set request.jwt.claim.sub='${admin}'`);
assert.deepEqual((await batch('cozinha',[oldConsumption],profile,oldId)).rows[0].body,oldBatch);
const a=await consumption('cozinha',2350),b=await consumption('cozinha',1650);
const kitchenId=randomUUID();const kitchen=(await batch('cozinha',[oldConsumption,a,b],profile,kitchenId)).rows[0].body;
assert.equal(text(kitchen),'000125;4\r\n');assert.deepEqual(kitchen.profile.order,['code','quantity']);assert.equal(kitchen.skipped_count,1);
assert.deepEqual((await batch('cozinha',[oldConsumption,a,b],profile,kitchenId)).rows[0].body,kitchen);
await assert.rejects(()=>batch('cozinha',[a,b]));
const bakeryConsumption=await consumption('padaria',1),bakery=(await batch('padaria',[bakeryConsumption],{...profile,order:['code','quantity'],header:true,separator:'|',decimal:'.',line_ending:'LF'})).rows[0].body;
assert.equal(text(bakery),'code|quantity\n000125|0.001\n');
const hortiConsumption=await consumption('hortifruti',2000);
await assert.rejects(()=>batch('hortifruti',[hortiConsumption],{...profile,order:['code','quantity']}));
const horti=(await batch('hortifruti',[hortiConsumption])).rows[0].body;assert.equal(text(horti),'000125;2;1;0,5\r\n');
await assert.rejects(()=>batch('padaria',[a]));
await db.exec(`set request.jwt.claim.sub='${operator}'`);await assert.rejects(()=>batch('padaria',[bakeryConsumption]));
console.log('PASS: exportação 006 com duas colunas Cozinha/Padaria, quatro Horti Fruti, precisão KG, agrupamento, proteção contra reexportação, RLS e lotes históricos imutáveis');
await db.close();
