import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create schema auth; create table auth.users(id uuid primary key); create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$; grant usage on schema auth to authenticated; grant execute on function auth.uid() to authenticated;`);
await db.exec(fs.readFileSync(new URL('../supabase/schema.sql',import.meta.url),'utf8'));
await db.exec(fs.readFileSync(new URL('../supabase/migrations/002_exports_v2.sql',import.meta.url),'utf8'));
const store='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222',op='33333333-3333-4333-8333-333333333333',product='44444444-4444-4444-8444-444444444444',device='55555555-5555-4555-8555-555555555555',other='66666666-6666-4666-8666-666666666666';
await db.exec(`insert into auth.users values('${user}'),('${other}'); insert into stores values('${store}','Loja'); insert into memberships values('${store}','${user}','admin'); set role authenticated; set request.jwt.claim.sub='${user}';`);
const p={id:product,code:'0001',description:'Arroz',unit:'UN',active:true,photo:null,version:1};
const apply=(id,kind,version,body)=>db.query('select apply_operation($1,$2,$3,$4,$5,$6::jsonb) as result',[store,id,device,kind,version,JSON.stringify(body)]);
await apply(op,'product',0,p);
assert.equal((await apply(op,'product',0,p)).rows[0].result.duplicate,true);
await assert.rejects(()=>apply(op,'product',0,{...p,description:'Tampered'}));
await assert.rejects(()=>apply('77777777-7777-4777-8777-777777777777','product',0,{...p,id:'88888888-8888-4888-8888-888888888888'}));
const c={id:'99999999-9999-4999-8999-999999999999',date:'2026-09-30',created_at:'2026-09-30T00:00:00Z',operator:'Ana',sector:'Padaria',note:'',status:'confirmed',version:1,cancellation_reason:null,items:[{id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',product_id:product,code:'0001',description:'Arroz',unit:'UN',amount:3000,total_cents:1350}]};
await assert.rejects(()=>apply('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','consumption',0,{...c,items:[{...c.items[0],amount:1500}]}));
await apply('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','consumption',0,c);
await assert.rejects(()=>apply('cccccccc-cccc-4ccc-8ccc-cccccccccccc','consumption',1,{...c,status:'cancelled',version:2,cancellation_reason:'Erro',items:[{...c.items[0],total_cents:1}]}));
await apply('cccccccc-cccc-4ccc-8ccc-cccccccccccc','consumption',1,{...c,status:'cancelled',version:2,cancellation_reason:'Erro'});
await assert.rejects(()=>db.exec(`delete from entities`));
await db.exec(`set request.jwt.claim.sub='${other}'`);
assert.equal((await db.query('select * from entities')).rows.length,0);
await assert.rejects(()=>apply('dddddddd-dddd-4ddd-8ddd-dddddddddddd','product',1,{...p,version:2}));
await db.exec(`reset role; insert into memberships values('${store}','${other}','operator'); set role authenticated;`);
assert.equal((await db.query('select * from entities')).rows.length,1);
await assert.rejects(()=>apply('dddddddd-dddd-4ddd-8ddd-dddddddddddd','product',1,{...p,version:2}));

await db.exec(`set request.jwt.claim.sub='${user}'`);
await assert.rejects(()=>apply(randomUUID(),'product',0,{...p,id:randomUUID(),code:123}));
const kgProduct={...p,id:randomUUID(),code:'00210',description:'Carne bovina',unit:'KG'};
await apply(randomUUID(),'product',0,kgProduct);
const c2={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID()}, {...c.items[0],id:randomUUID(),product_id:kgProduct.id,code:kgProduct.code,description:kgProduct.description,unit:'KG',amount:2350,total_cents:7050}]};
await assert.rejects(()=>apply(randomUUID(),'consumption',0,{...c2,items:[{...c2.items[0],amount:'3000'}]}));
await apply(randomUUID(),'consumption',0,c2);
const selection=[{consumption_id:c2.id,item_id:c2.items[0].id,version:1}];
const batchId=randomUUID();
const batch=(id,items)=>db.query('select create_export_batch($1,$2,$3::jsonb) as body',[store,id,JSON.stringify(items)]);
const update=(id,version,action,ref)=>db.query('select update_export_batch($1,$2,$3,$4,$5) as body',[store,id,version,action,ref]);
assert.equal((await batch(batchId,selection)).rows[0].body.status,'prepared');
assert.equal((await batch(batchId,selection)).rows[0].body.id,batchId);
await assert.rejects(()=>batch(randomUUID(),selection));
await assert.rejects(()=>apply(randomUUID(),'consumption',1,{...c2,status:'cancelled',version:2,cancellation_reason:'Erro'}));
await assert.rejects(()=>update(batchId,null,'cancelled','Erro no lote'));
assert.equal((await update(batchId,1,'cancelled','Erro no lote')).rows[0].body.status,'cancelled');
const secondBatchId=randomUUID();
await batch(secondBatchId,selection);
assert.equal((await update(secondBatchId,1,'issued','Nota 1234')).rows[0].body.status,'issued');
assert.equal((await update(secondBatchId,1,'issued','Nota 1234')).rows[0].body.status,'issued');
await assert.rejects(()=>update(secondBatchId,2,'cancelled','Desfazer emissão'));
await db.exec(`set request.jwt.claim.sub='${other}'`);
assert.equal((await db.query('select * from export_batches')).rows.length,0);
await assert.rejects(()=>batch(randomUUID(),selection));
await db.exec(`set request.jwt.claim.sub='${user}'`);
const c3={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID(),amount:2000,total_cents:6101}]};
const c4={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID(),amount:3000,total_cents:9256}]};
await apply(randomUUID(),'consumption',0,c3); await apply(randomUUID(),'consumption',0,c4);
const sel=[c3,c4].map(c=>({consumption_id:c.id,item_id:c.items[0].id,version:1}));
const profile={version:1,separator:';',decimal:',',encoding:'UTF8',line_ending:'CRLF',header:false,bom:false,fixed_price:false,validated:true,order:['code','quantity','unit','unit_price']};
const b2=(id,items=sel,pr=profile)=>db.query('select create_export_batch_v2($1,$2,$3::jsonb,$4::jsonb,$5::jsonb) as body',[store,id,JSON.stringify(items),JSON.stringify(pr),'{}']);
const change2=(id,v,action,ref='',event=randomUUID())=>db.query('select update_export_batch_v2($1,$2,$3,$4,$5,$6) as body',[store,id,v,action,ref,event]);
await assert.rejects(()=>b2(randomUUID(),sel,{...profile,validated:false}));
await assert.rejects(()=>b2(randomUUID(),sel,{...profile,order:['code','code','unit','quantity']}));
const id2=randomUUID();
const result2=(await b2(id2)).rows[0].body;
assert.equal(Buffer.from(result2.artifact.base64,'base64').toString('utf8'),'0001;5;1;30,714\r\n');
assert.equal(result2.grouped_rows.length,1);
assert.equal(result2.grouped_rows[0].price4,'307140');
const {createHash}=await import('node:crypto');
assert.equal(result2.artifact.sha256,createHash('sha256').update(Buffer.from(result2.artifact.base64,'base64')).digest('hex'));
assert.deepEqual((await b2(id2)).rows[0].body,result2);
await assert.rejects(()=>b2(id2,sel,{...profile,decimal:'.'}));
await assert.rejects(()=>b2(randomUUID()));
await assert.rejects(()=>update(id2,1,'cancelled','Cliente antigo'));
const authEvent=randomUUID();
const ready=(await change2(id2,1,'authorize_save','',authEvent)).rows[0].body;
assert.equal(ready.status,'ready');
assert.deepEqual((await change2(id2,1,'authorize_save','',authEvent)).rows[0].body,ready);
await assert.rejects(()=>change2(id2,ready.version,'cancelled','Arquivo pode existir'));
await assert.rejects(()=>change2(id2,ready.version,'imported','Importação teste'));
const savedEvent=randomUUID();
const saved=(await change2(id2,ready.version,'saved','',savedEvent)).rows[0].body;
assert.equal(saved.status,'downloaded');
assert.deepEqual((await change2(id2,ready.version,'saved','',savedEvent)).rows[0].body,saved);
await assert.rejects(()=>change2(id2,saved.version,'imported','Outro',savedEvent));
const imported=(await change2(id2,saved.version,'imported','Conferido no VR')).rows[0].body;
assert.equal(imported.status,'imported');
assert.deepEqual(imported.artifact,result2.artifact);
assert.equal((await db.query('select body from export_batches where id=$1',[secondBatchId])).rows[0].body.status,'issued');
// Numeric rounding and minimum KG quantity match the client contract.
const c5={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID(),product_id:kgProduct.id,code:kgProduct.code,description:kgProduct.description,unit:'KG',amount:3,total_cents:2}]};
await apply(randomUUID(),'consumption',0,c5);
const kgSel=[{consumption_id:c5.id,item_id:c5.items[0].id,version:1}];
const kgId=randomUUID();
const kgBatch=(await b2(kgId,kgSel,{...profile,decimal:'.',fixed_price:true,header:true,order:['unit_price','unit','quantity','code']})).rows[0].body;
assert.equal(Buffer.from(kgBatch.artifact.base64,'base64').toString('utf8'),'unit_price;unit;quantity;code\r\n6.6667;1;0.003;00210\r\n');
assert.equal(kgBatch.grouped_rows[0].difference7,'1');
await change2(kgId,1,'cancelled','Teste encerrado');
await b2(randomUUID(),kgSel);
await db.exec(`set request.jwt.claim.sub='${other}'`);
await assert.rejects(()=>b2(randomUUID(),kgSel));
await assert.rejects(()=>change2(id2,imported.version,'saved'));
await db.exec(`set request.jwt.claim.sub='${user}'`);
const oldMeasure={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID(),amount:1000,total_cents:100}]};
await apply(randomUUID(),'consumption',0,oldMeasure);
await apply(randomUUID(),'product',1,{...p,unit:'KG',version:2});
const newMeasure={...c,id:randomUUID(),items:[{...c.items[0],id:randomUUID(),unit:'KG',amount:1000,total_cents:100}]};
await apply(randomUUID(),'consumption',0,newMeasure);
const mixedSelection=[oldMeasure,newMeasure].map(c=>({consumption_id:c.id,item_id:c.items[0].id,version:1}));
const rejectedId=randomUUID();
await assert.rejects(()=>b2(rejectedId,mixedSelection));
assert.equal((await db.query('select count(*)::integer as n from export_batches where id=$1',[rejectedId])).rows[0].n,0);
// Rollback must also free every temporary reservation made inside the failed transaction.
await b2(randomUUID(),[mixedSelection[0]]);
console.log('PASS: operações/RLS legadas e exportação v2: agrupamento, precisão, SHA-256, reservas exclusivas, perfis, eventos idempotentes, estados e preservação de histórico');
await db.close();
